=== musicindexonline/data/schemas/v2/works.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://musicindexonline.github.io/data/schemas/v2/works.schema.json",
  "title": "Music Index Online works",
  "type": "array",
  "definitions": {
    "stringSet": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "composerId",
      "workId",
      "title",
      "genre",
      "movements"
    ],
    "properties": {
      "composerId": {
        "type": "string",
        "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      },
      "workId": {
        "type": "string",
        "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      },
      "title": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "preferred"
        ],
        "properties": {
          "preferred": {
            "type": "string",
            "minLength": 1
          },
          "alias": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "identifiers": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "catalog",
            "value"
          ],
          "properties": {
            "catalog": {
              "type": "string",
              "pattern": "^[a-z][a-z0-9-]*$"
            },
            "value": {
              "type": "string",
              "minLength": 1
            },
            "display": {
              "type": "string",
              "minLength": 1
            },
            "primary": {
              "type": "boolean"
            }
          }
        }
      },
      "medium": {
        "$ref": "#/definitions/stringSet"
      },
      "genre": {
        "type": "string",
        "minLength": 1
      },
      "key": {
        "$ref": "#/definitions/stringSet"
      },
      "period": {
        "type": "string",
        "enum": [
          "Baroque",
          "Classical",
          "Romantic",
          "Modern"
        ]
      },
      "movements": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "title"
          ],
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "key": {
              "$ref": "#/definitions/stringSet"
            },
            "medium": {
              "$ref": "#/definitions/stringSet"
            }
          }
        }
      }
    }
  }
}

=== musicindexonline/data/source/v2/works.json
[
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-concerto-for-strings-in-c-major-rv-114",
    "title": { "preferred": "Concerto for Strings in C Major" },
    "identifiers": [
      { "catalog": "rv", "value": "114", "display": "RV 114", "primary": true },
      { "catalog": "p", "value": "27", "display": "P. 27", "primary": false },
      { "catalog": "f", "value": "XI. n. 44", "display": "F. XI. n. 44", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["C Major"],
    "medium": ["violin", "viola", "cello", "continuo"],
    "movements": [
      { "title": "I. Allegro" },
      { "title": "II. Adagio" },
      { "title": "III. Ciaccona. Allegro ma non troppo" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-concerto-for-strings-in-g-major-rv-151",
    "title": { "preferred": "Concerto for Strings in G Major", "alias": "Alla Rustica" },
    "identifiers": [
      { "catalog": "rv", "value": "151", "display": "RV 151", "primary": true },
      { "catalog": "op", "value": "51/4", "display": "Op. 5 No. 4", "primary": false },
      { "catalog": "p", "value": "143", "display": "P. 143", "primary": false },
      { "catalog": "f", "value": "XI n. 11", "display": "F. XI n. 11", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["G Major"],
    "medium": ["violin", "viola", "cello", "oboe", "continuo"],
    "movements": [
      { "title": "I. Presto", "medium": ["violin", "viola", "cello", "continuo"] },
      { "title": "II. Adagio", "medium": ["violin", "viola", "cello", "continuo"] },
      { "title": "III. Allegro", "medium": ["violin", "viola", "cello", "oboe", "continuo"] }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-violin-concerto-no-1-in-e-major-rv-269",
    "title": { "preferred": "Violin Concerto No. 1 in E Major", "alias": "La primavera" },
    "identifiers": [
      { "catalog": "rv", "value": "269", "display": "RV 269", "primary": true },
      { "catalog": "op", "value": "8/1", "display": "Op. 8 No. 1", "primary": false },
      { "catalog": "p", "value": "241", "display": "P. 241", "primary": false },
      { "catalog": "f", "value": "I n. 22", "display": "F. I n. 22", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["E Major"],
    "medium": ["violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro" },
      { "title": "II. Largo e pianissimo sempre" },
      { "title": "III. Danza pastorale. Allegro" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-violin-concerto-no-3-in-f-major-rv-293",
    "title": { "preferred": "Violin Concerto No. 3 in F Major", "alias": "L'autunno" },
    "identifiers": [
      { "catalog": "rv", "value": "293", "display": "RV 293", "primary": true },
      { "catalog": "op", "value": "8/3", "display": "Op. 8 No. 3", "primary": false },
      { "catalog": "p", "value": "257", "display": "P. 257", "primary": false },
      { "catalog": "f", "value": "I n. 24", "display": "F. I n. 24", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["F Major"],
    "medium": ["violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro" },
      { "title": "II. Adagio molto" },
      { "title": "III. Allegro" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-violin-concerto-no-4-in-f-minor-rv-297",
    "title": { "preferred": "Violin Concerto No. 4 in F Minor", "alias": "L'inverno" },
    "identifiers": [
      { "catalog": "rv", "value": "297", "display": "RV 297", "primary": true },
      { "catalog": "op", "value": "8/4", "display": "Op. 8 No. 4", "primary": false },
      { "catalog": "p", "value": "442", "display": "P. 442", "primary": false },
      { "catalog": "f", "value": "I n. 25", "display": "F. I n. 25", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["F Minor"],
    "medium": ["violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro non molto" },
      { "title": "II. Largo" },
      { "title": "III. Allegro" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-violin-concerto-no-2-in-g-minor-rv-315",
    "title": { "preferred": "Violin Concerto No. 2 in G Minor", "alias": "L'estate" },
    "identifiers": [
      { "catalog": "rv", "value": "315", "display": "RV 315", "primary": true },
      { "catalog": "op", "value": "8/2", "display": "Op. 8 No. 2", "primary": false },
      { "catalog": "p", "value": "336", "display": "P. 336", "primary": false },
      { "catalog": "f", "value": "I n. 23", "display": "F. I n. 23", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["G Minor"],
    "medium": ["violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro non molto" },
      { "title": "II. Adagio e piano - Presto e forte" },
      { "title": "III. Presto" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-concerto-no-6-in-a-minor-rv-356",
    "title": { "preferred": "Concerto No. 6 in A Minor" },
    "identifiers": [
      { "catalog": "rv", "value": "356", "display": "RV 356", "primary": true },
      { "catalog": "op", "value": "3/6", "display": "Op. 3 No. 6", "primary": false },
      { "catalog": "p", "value": "1", "display": "P. 1", "primary": false },
      { "catalog": "f", "value": "I n. 176", "display": "F. I n. 176", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["A Minor"],
    "medium": ["violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro" },
      { "title": "II. Largo" },
      { "title": "III. Presto" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-concerto-for-2-violins-strings-and-continuo-in-g-major-rv-516",
    "title": { "preferred": "Concerto for 2 Violins, Strings and Continuo in G Major" },
    "identifiers": [
      { "catalog": "rv", "value": "516", "display": "RV 516", "primary": true },
      { "catalog": "p", "value": "132", "display": "P. 132", "primary": false },
      { "catalog": "f", "value": "I n. 6", "display": "F. I n. 6", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["G Major"],
    "medium": ["violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro molto" },
      { "title": "II. Andante molto" },
      { "title": "III. Allegro" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-concerto-for-oboe-violin-strings-and-continuo-in-bflat-major-rv-548",
    "title": { "preferred": "Concerto for Oboe, Violin, Strings and Continuo in B-Flat Major" },
    "identifiers": [
      { "catalog": "rv", "value": "548", "display": "RV 548", "primary": true },
      { "catalog": "op", "value": "52", "display": "Op. 52", "primary": false },
      { "catalog": "p", "value": "406", "display": "P. 406", "primary": false },
      { "catalog": "f", "value": "XII n. 16", "display": "F. XII n. 16", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["B-Flat Major"],
    "medium": ["oboe", "violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro" },
      { "title": "II. Largo" },
      { "title": "III. Allegro" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-concerto-for-3-violins-in-f-major-rv-551",
    "title": { "preferred": "Concerto for 3 Violins in F Major" },
    "identifiers": [
      { "catalog": "rv", "value": "551", "display": "RV 551", "primary": true },
      { "catalog": "p", "value": "278", "display": "P. 278", "primary": false },
      { "catalog": "f", "value": "I n. 34", "display": "F. I n. 34", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["F Major"],
    "medium": ["violin", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro" },
      { "title": "II. Andante" },
      { "title": "III. Allegro" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-concerto-no-10-for-4-violins-and-cello-in-b-minor-rv-580",
    "title": { "preferred": "Concerto No. 10 for 4 Violins and Cello in B Minor" },
    "identifiers": [
      { "catalog": "rv", "value": "580", "display": "RV 580", "primary": true },
      { "catalog": "op", "value": "3/10", "display": "Op. 3 No. 10", "primary": false },
      { "catalog": "p", "value": "148", "display": "P. 148", "primary": false },
      { "catalog": "f", "value": "IV n. 10", "display": "F. IV n. 10", "primary": false }
    ],
    "genre": "Concerto",
    "key": ["B Minor"],
    "medium": ["violin", "cello", "strings", "continuo"],
    "movements": [
      { "title": "I. Allegro" },
      { "title": "II. Larghetto e spiccato" },
      { "title": "III. Allegro" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-il-giustino-rv-717",
    "title": { "preferred": "Il Giustino" },
    "identifiers": [
      { "catalog": "rv", "value": "717", "display": "RV 717", "primary": true }
    ],
    "genre": "Opera",
    "movements": [
      { "title": "Sinfonia" },
      { "title": "Atto primo" },
      { "title": "Atto secondo" },
      { "title": "Atto terzo" }
    ]
  },
  {
    "composerId": "antonio-vivaldi",
    "workId": "antonio-vivaldi-lolimpiade-rv-725",
    "title": { "preferred": "L'Olimpiade" },
    "identifiers": [
      { "catalog": "rv", "value": "725", "display": "RV 725", "primary": true }
    ],
    "genre": "Opera",
    "movements": [
      { "title": "Sinfonia" },
      { "title": "Atto primo" },
      { "title": "Atto secondo" },
      { "title": "Atto terzo" }
    ]
  },
  {
    "composerId": "georg-melchior-hoffmann",
    "workId": "georg-melchior-hoffmann-schlage-doch-gewunschte-stunde-bwv-53",
    "title": { "preferred": "Schlage doch, gewünschte Stunde" },
    "identifiers": [
      { "catalog": "bwv", "value": "53", "display": "BWV 53", "primary": true }
    ],
